language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: CZq7GRFLNabkY3OtHcLv0O9qCu3LSNXXy8yoTEZ6NRav2jDhaGWlYJvl+sMDWMYa0jAjq2AfX+Ask4srFDZPV18ZVSPfaJJcRypc6A52ccPLdTJ4pniXfpkWDWW07TxBvGvP0dt6LwAWn5JDaNAPhKhY6kvsGHlF2nGAq6kKTti1WkBi9v1Z0j124gXLIlrRuibvbp4paQHl8CHa5GgIaYswDtbkE4sM1kwHk3cJm56jxHVdeune8VJK0BiAUF06C6JK3Do5KlwMd0Hunqx16zDBnaxOuGjtailzDi8fnP4Dh6EbzKXaozT9BwQR01IE5EHNO7/+k01ZZ+lv+2PfIAT4/3+FRTpdtVyu9dm5RRRhMXjlMpSTAr1R7qNF4eO/ymSLtAvOpXJBKPcmBqtJy3+Y6dPa78NtB4bJkjtDzFHN/FOExwY7aZIgC3BYiwkZk1mvAf0YYdqS9WZtMsWRhV0rC0EjiMlV9pSfIOX7RiQILbsQWjhhOggUN6nbLLz1Uql2WpyQFjDEVXF1PKv7wynp/6zfg84KXRFeKia/GHWrs2gQF8MfIEhB07JNhn1XjNNJ+hsTReFJ9vucU8sq1tD5gXUsm+TkAA4PhgMBVMoUCr3MIx5GeP7B0GGk3U0ff6kGo5GQ0FJrZdjMsmvzxOsi2wR2Wh6RAy5YzaqWdUc=
  app: liamgowan-email-validator-ui
  on:
    repo: liamgowan/email-validator-ui
