language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: vHdFeb/CbknsmuEUquOlEeDshtjAEoXGUpcZd7YD4UKOchnx+LYOk/BqMEIX5tmRcIiXgt9JQQm6BIBeI8MYEG4OpgANcahmKs5eyDGmJHOefQ6/zW+velLfvuk82vByELniI4vlMD5hi7MFTO4wLfp9O6dtVlGs/plRdPXOA7thtodel0JIrPPD/kFelESI4B+CKjlLAc7UNfDUO1HY34wYof6yOAsOp/6FtY36aDpar5DO3mumK8AnjVKVSfK54yF74EhaaCAN2F2jhlwYHrSh07Zolga8QFsfXTbTHoi+oLuYf2/63b4SyMX32GFEYFP0Q4/i2BI2VeGLHQf/f/GuxwxfzYgynw3j806RwSTp/OhGyWmWesI2W2gt5Y17/LxGK7dzJibBRv9b9iIanUvCbTNuaGYRvVpnJx7tImN8ZruwW7lFjVr90a58K/068rk0qpl4kKpDpsVrY1yuluc52BEFVBqphZ3eLRbIzcz19YJk5pX+fHaiRCNRZYqqq8wKu/wx4tKZz0lrIiNGO3uEN8dM09M9QmslJx/DV86Y4zjoO8nFD/Mcapzc1TvfGvrBH7VK+EQeJ+p2bdBGIwdXm894LbR45J93m+7KqfSXeqerqFulV4FeICxjjY19NeywBNoAyXE/FAunol6jBTbfyyBUdv64Uwrdl8Xh0sQ=
  app: liamgowan-email-validator-ui
  on:
    repo: liamgowan/email-validator-ui
